# Generated by Django 5.0.6 on 2026-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oauth_id",
            field=models.CharField(
                blank=True, help_text="OAuthプロバイダーでのユーザーID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="oauth_provider",
            field=models.CharField(
                blank=True,
                help_text="OAuth認証プロバイダー（google, github等）",
                max_length=50,
                null=True,
            ),
        ),
    ]
