# Generated by Django 5.0.6 on 2026-02-15 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_add_location_model"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visited_at", models.DateTimeField(verbose_name="訪問日時")),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="評価",
                    ),
                ),
                ("review", models.TextField(blank=True, verbose_name="レビュー")),
                (
                    "actual_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="trips.actualtrip",
                        verbose_name="実際の旅行",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="locations.location",
                        verbose_name="場所",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "訪問記録",
                "verbose_name_plural": "訪問記録",
                "db_table": "visits",
                "ordering": ["-visited_at"],
                "indexes": [
                    models.Index(fields=["user", "visited_at"], name="visits_user_id_2780bf_idx"),
                    models.Index(
                        fields=["location", "visited_at"], name="visits_locatio_bea25e_idx"
                    ),
                ],
            },
        ),
    ]
