# Generated by Django 5.0.6 on 2026-01-30 13:43

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
                ("slug", models.SlugField(unique=True, verbose_name="スラッグ")),
                ("icon", models.CharField(blank=True, max_length=50, verbose_name="アイコン")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="locations.category",
                        verbose_name="親カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
                "db_table": "categories",
            },
        ),
    ]
