# Generated by Django 5.0.6 on 2026-02-08 22:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="場所名")),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name="座標"),
                ),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="タグ")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("want_to_visit", "行きたい"), ("not_interested", "興味なし")],
                        max_length=20,
                        null=True,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                ("website", models.URLField(blank=True, verbose_name="Webサイト")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="電話番号")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="locations.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "場所",
                "verbose_name_plural": "場所",
                "db_table": "locations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "category"], name="locations_user_id_1fdc65_idx"),
                    models.Index(fields=["user", "status"], name="locations_user_id_e40f81_idx"),
                ],
            },
        ),
    ]
