# Generated by Django 5.0.6 on 2026-02-15 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="旅行名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="開始日")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="終了日")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_trips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "旅行計画",
                "verbose_name_plural": "旅行計画",
                "db_table": "planned_trips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActualTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="旅行名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("end_date", models.DateField(verbose_name="終了日")),
                (
                    "overall_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="総合評価",
                    ),
                ),
                ("overall_review", models.TextField(blank=True, verbose_name="総合レビュー")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_trips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "planned_trip",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actual_trip",
                        to="trips.plannedtrip",
                        verbose_name="元の計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "実際の旅行",
                "verbose_name_plural": "実際の旅行",
                "db_table": "actual_trips",
                "ordering": ["-start_date"],
            },
        ),
    ]
